databases:
  - name: gift_boutique 
    databaseName: gift_boutique
    user: gift_boutique

services:
  - type: web
    name: gift_boutique
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gift_boutique
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false